Adding to lib logger 1.2.8
It appears that the yanked 1.2.8 version is substantively different
than the 1.2.7 version (which was minted recently). The following error
occurred on Travis.

```console
SyntaxError: ./logger-1.2.7/lib/logger.rb:482: syntax error, unexpected '.'
    @logdev&.write(msg)
             ^
./logger-1.2.7/lib/logger.rb:569: syntax error, unexpected '.'
    @logdev&.close
             ^
```