Addressing load issue in Document
Adding an explicit load for the RDF::ND module. In development,
I encountered the following error:

```console
NameError: uninitialized constant RDF::ND
```

In production this manifested in the Document class not having
the correct predicates in it's inspect. If Document were the first
of the repository models loaded, then the class would say something
like:

```console
Document.new.title
NoMethodError <#Document> does not respond to :title
```

If Document were loaded after other repository models (e.g Image), then
we wouldn't encounter the error, and the Document would have the
expected attributes.

For workers, since usually load one model at a time, they would always
encounter this error. But for web-application facing, they would not,
as Document is one amongst many objects that could be loaded.

DLTP-1520